# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""processAgentWebhook_request_data

    ProcessAgentWebhookRequestData(; value=nothing)
"""
mutable struct ProcessAgentWebhookRequestData <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Any, Bool, Float64, String, Vector{Any} }
    ProcessAgentWebhookRequestData() = new()
    ProcessAgentWebhookRequestData(value) = new(value)
end # type ProcessAgentWebhookRequestData

function OpenAPI.property_type(::Type{ ProcessAgentWebhookRequestData }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(ProcessAgentWebhookRequestData, name)
end
