# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""processAgentWebhook_request
A payload to be passed to the agent

    ProcessAgentWebhookRequest(;
        data=nothing,
    )

    - data::ProcessAgentWebhookRequestData
"""
Base.@kwdef mutable struct ProcessAgentWebhookRequest <: OpenAPI.APIModel
    data = nothing # spec type: Union{ Nothing, ProcessAgentWebhookRequestData }

    function ProcessAgentWebhookRequest(data, )
        OpenAPI.validate_property(ProcessAgentWebhookRequest, Symbol("data"), data)
        return new(data, )
    end
end # type ProcessAgentWebhookRequest

const _property_types_ProcessAgentWebhookRequest = Dict{Symbol,String}(Symbol("data")=>"ProcessAgentWebhookRequestData", )
OpenAPI.property_type(::Type{ ProcessAgentWebhookRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProcessAgentWebhookRequest[name]))}

function check_required(o::ProcessAgentWebhookRequest)
    true
end

function OpenAPI.validate_property(::Type{ ProcessAgentWebhookRequest }, name::Symbol, val)
end
