# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Agent

    Agent(;
        id=nothing,
    )

    - id::String
"""
Base.@kwdef mutable struct Agent <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing

    function Agent(id, )
        OpenAPI.validate_property(Agent, Symbol("id"), id)
        return new(id, )
    end
end # type Agent

const _property_types_Agent = Dict{Symbol,String}(Symbol("id")=>"String", )
OpenAPI.property_type(::Type{ Agent }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Agent[name]))}

function check_required(o::Agent)
    true
end

function OpenAPI.validate_property(::Type{ Agent }, name::Symbol, val)
end
